const journalistData = [
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-01.png",
    rank: 1,
    name: "데이비드 온스테인",
    media: "디 애슬레틱",
    team: "프리미어리그 전체",
    roles: ["이적시장 전문보도", "단독 기사", "독점 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-02.png",
    rank: 2,
    name: "올리버 케이",
    media: "디 애슬레틱",
    team: "프리미어리그 전체",
    roles: ["이적 비하인드 스토리", "내막 보도"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-03.png",
    rank: 3,
    name: "다니엘 테일러",
    media: "디 애슬레틱",
    team: "프리미어리그",
    roles: ["탐사보도", "스캔들 폭로"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-04.png",
    rank: 4,
    name: "마이클 콕스",
    media: "디 애슬레틱",
    team: "전체",
    roles: ["전술 분석"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-05.png",
    rank: 5,
    name: "닉 밀러",
    media: "디 애슬레틱",
    team: "전체",
    roles: ["데이터 분석"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-06.png",
    rank: 6,
    name: "칼 안카",
    media: "디 애슬레틱",
    team: "맨체스터 유나이티드",
    roles: ["전술 분석"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-07.png",
    rank: 7,
    name: "로리 휘트웰",
    media: "디 애슬레틱",
    team: "맨체스터 유나이티드",
    roles: ["구단 전담", "이적시장 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-08.png",
    rank: 8,
    name: "앤디 미튼",
    media: "디 애슬레틱",
    team: "맨체스터 유나이티드",
    roles: ["인터뷰", "구단 내부 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-09.png",
    rank: 9,
    name: "아담 크래프턴",
    media: "디 애슬레틱",
    team: "맨체스터 유나이티드, EPL, 라리가",
    roles: ["이적시장 보도", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-10.png",
    rank: 10,
    name: "댄 쉘던",
    media: "디 애슬레틱",
    team: "맨체스터",
    roles: ["내부 소식", "구단 운영"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-11.png",
    rank: 11,
    name: "마크 크리츨리",
    media: "디 애슬레틱",
    team: "맨체스터",
    roles: ["구단 소식", "지역 특파"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-12.png",
    rank: 12,
    name: "제임스 피어스",
    media: "디 애슬레틱",
    team: "리버풀",
    roles: ["Q&A", "구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-13.png",
    rank: 13,
    name: "퀴바 오닐",
    media: "디 애슬레틱",
    team: "리버풀, 루턴 타운",
    roles: ["라이브 리포팅", "아카데미 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-14.png",
    rank: 14,
    name: "사이먼 휴즈",
    media: "디 애슬레틱",
    team: "리버풀",
    roles: ["구단 소식", "분석"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-15.png",
    rank: 15,
    name: "샘 리",
    media: "디 애슬레틱",
    team: "맨체스터 시티",
    roles: ["구단 소식", "이적시장"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-16.png",
    rank: 16,
    name: "사이먼 존슨",
    media: "디 애슬레틱",
    team: "첼시",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-17.png",
    rank: 17,
    name: "리암 투메이",
    media: "디 애슬레틱",
    team: "첼시",
    roles: ["구단 소식", "특파 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-18.png",
    rank: 18,
    name: "에이미 로렌스",
    media: "디 애슬레틱",
    team: "아스날",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-19.png",
    rank: 19,
    name: "아르 드 로쉐",
    media: "디 애슬레틱",
    team: "아스날",
    roles: ["구단 소식", "분석"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-20.png",
    rank: 20,
    name: "제임스 맥니콜라스",
    media: "디 애슬레틱",
    team: "아스날",
    roles: ["구단 소식", "팬 커뮤니티"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-21.png",
    rank: 21,
    name: "조던 캠벨",
    media: "디 애슬레틱",
    team: "아스날",
    roles: ["분석글", "전술 분석"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-22.png",
    rank: 22,
    name: "마리오 코르테가나",
    media: "디 애슬레틱",
    team: "레알 마드리드",
    roles: ["구단 내부 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-23.png",
    rank: 23,
    name: "기예르모 라이",
    media: "디 애슬레틱",
    team: "레알 마드리드",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-24.png",
    rank: 24,
    name: "폴 발루스",
    media: "디 애슬레틱",
    team: "바르셀로나, 맨체스터 시티",
    roles: ["펩 과르디올라 전담", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-25.png",
    rank: 25,
    name: "도미닉 피필드",
    media: "디 애슬레틱",
    team: "프리미어리그 전체",
    roles: ["구단 소식", "분석"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-26.png",
    rank: 26,
    name: "그렉 오키프",
    media: "디 애슬레틱",
    team: "에버튼",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-27.png",
    rank: 27,
    name: "패트릭 보이랜드",
    media: "디 애슬레틱",
    team: "에버튼",
    roles: ["구단 소식", "보조 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-28.png",
    rank: 28,
    name: "찰리 애클리셰어",
    media: "디 애슬레틱",
    team: "토트넘",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-29.png",
    rank: 29,
    name: "잭 피트 부르크",
    media: "디 애슬레틱",
    team: "토트넘",
    roles: ["구단 소식", "분석"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-30.png",
    rank: 30,
    name: "앤디 네일러",
    media: "디 애슬레틱",
    team: "브라이튼",
    roles: ["구단 소식", "지역 특파"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-31.png",
    rank: 31,
    name: "제이콥 화이트헤드",
    media: "디 애슬레틱",
    team: "뉴캐슬",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-32.png",
    rank: 32,
    name: "크리스 와그",
    media: "디 애슬레틱",
    team: "뉴캐슬",
    roles: ["구단 소식", "지역 보도"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-33.png",
    rank: 33,
    name: "조지 컬킨",
    media: "디 애슬레틱",
    team: "영국 북동부",
    roles: ["지역 특파", "구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-34.png",
    rank: 34,
    name: "팀 스피어스",
    media: "디 애슬레틱",
    team: "토트넘, 런던, 울버햄튼",
    roles: ["분석글", "경기 리포트"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-35.png",
    rank: 35,
    name: "스티브 메들리",
    media: "디 애슬레틱",
    team: "울버햄튼",
    roles: ["내부 소식", "구단 운영"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-36.png",
    rank: 36,
    name: "제이 해리스",
    media: "디 애슬레틱",
    team: "브렌트포드",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-37.png",
    rank: 37,
    name: "피터 루츨러",
    media: "디 애슬레틱",
    team: "풀럼, 파리 생제르맹",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-38.png",
    rank: 38,
    name: "맷 우스남",
    media: "디 애슬레틱",
    team: "크리스탈 팰리스",
    roles: ["구단 소식", "분석"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-39.png",
    rank: 39,
    name: "로셰인 토마스",
    media: "디 애슬레틱",
    team: "웨스트햄",
    roles: ["구단 소식", "이적시장"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "디 애슬레틱",
    img: "../img/profile-img/face/face-40.png",
    rank: 40,
    name: "필 헤이",
    media: "디 애슬레틱",
    team: "리즈",
    roles: ["구단 소식", "이적시장"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-41.png",
    rank: 1,
    name: "사이먼 스톤",
    media: "BBC",
    team: "맨체스터 유나이티드, 맨체스터 시티, EPL",
    roles: ["구단 소식", "이적시장 보도", "확정 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-42.png",
    rank: 2,
    name: "하워드 너스",
    media: "BBC",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식", "이적시장 보도", "종결 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-43.png",
    rank: 3,
    name: "니자르 킨셀라",
    media: "BBC",
    team: "첼시, 풀럼",
    roles: ["구단 소식", "이적시장 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-44.png",
    rank: 4,
    name: "아담 블랙모어",
    media: "BBC",
    team: "사우스햄튼",
    roles: ["구단 소식", "이적시장 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-45.png",
    rank: 5,
    name: "마이크 미나이",
    media: "BBC",
    team: "맨체스터 시티",
    roles: ["구단 소식", "이적시장 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-46.png",
    rank: 6,
    name: "필 맥널티",
    media: "BBC",
    team: "머지사이드",
    roles: ["수석 기자", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-47.png",
    rank: 7,
    name: "알렉스 호웰",
    media: "BBC",
    team: "브라이튼, 런던",
    roles: ["런던 특파원", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-48.png",
    rank: 8,
    name: "오윈 팔머 앳킨",
    media: "BBC",
    team: "레스터",
    roles: ["구단 소식", "이적시장 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-49.png",
    rank: 9,
    name: "엘코 보른",
    media: "BBC",
    team: "네덜란드",
    roles: ["해외 특파원", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-50.png",
    rank: 10,
    name: "오루와시나 오케레지",
    media: "BBC",
    team: "아프리카",
    roles: ["아프리카 축구 전담", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "BBC",
    img: "../img/profile-img/face/face-51.png",
    rank: 11,
    name: "기옴 발라그",
    media: "BBC",
    team: "프랑스, 스페인",
    roles: ["해외 특파원", "분석"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-52.png",
    rank: 1,
    name: "리알 토마스",
    media: "스카이 스포츠",
    team: "토트넘, EPL",
    roles: ["구단 소식", "프리미어리그 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-53.png",
    rank: 2,
    name: "멜리사 레디",
    media: "스카이 스포츠",
    team: "맨체스터 유나이티드, 리버풀, EPL",
    roles: ["구단 소식", "프리미어리그 보도"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-54.png",
    rank: 3,
    name: "키스 다우니",
    media: "스카이 스포츠",
    team: "뉴캐슬, 선덜랜드, 영국 북동부",
    roles: ["지역 특파원", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-55.png",
    rank: 4,
    name: "앨런 마이어스",
    media: "스카이 스포츠",
    team: "에버튼",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-56.png",
    rank: 5,
    name: "롭 도르셋",
    media: "스카이 스포츠",
    team: "레스터, 아스톤 빌라, 중부 지역",
    roles: ["구단 소식", "지역 특파원"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-57.png",
    rank: 6,
    name: "마이클 브릿지",
    media: "스카이 스포츠",
    team: "토트넘",
    roles: ["내부 기자"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-58.png",
    rank: 7,
    name: "다르메스 세스",
    media: "스카이 스포츠",
    team: "웨스트햄",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-59.png",
    rank: 8,
    name: "카베 쇼헤콜",
    media: "스카이 스포츠",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-30.png",
    rank: 9,
    name: "피트 그레이브스",
    media: "스카이 스포츠",
    team: "뉴캐슬",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "스카이 스포츠",
    img: "../img/profile-img/face/face-34.png",
    rank: 10,
    name: "벤 랜섬",
    media: "스카이 스포츠",
    team: "EPL",
    roles: ["진행자"],
    trust: 60,
    profileUrl: "#",
  },

  // The Telegraph
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-48.png",
    rank: 1,
    name: "맷 로",
    media: "텔레그래프",
    team: "첼시, 토트넘, 런던",
    roles: ["구단 소식", "런던팀 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-32.png",
    rank: 2,
    name: "제임스 더커",
    media: "텔레그래프",
    team: "맨체스터 유나이티드, 맨체스터 시티",
    roles: ["구단 소식", "맨유 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-33.png",
    rank: 3,
    name: "존 퍼시",
    media: "텔레그래프",
    team: "레스터, 노팅엄, EPL",
    roles: ["구단 소식", "중부 지역 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-34.png",
    rank: 4,
    name: "루크 에드워즈",
    media: "텔레그래프",
    team: "뉴캐슬",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-21.png",
    rank: 5,
    name: "크리스 바스콤",
    media: "텔레그래프",
    team: "머지사이드",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-22.png",
    rank: 6,
    name: "샘 왈라스",
    media: "텔레그래프",
    team: "EPL",
    roles: ["수석 기자", "구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-11.png",
    rank: 7,
    name: "샘 딘",
    media: "텔레그래프",
    team: "아스날, 첼시",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-12.png",
    rank: 8,
    name: "제이슨 버트",
    media: "텔레그래프",
    team: "맨체스터 유나이티드",
    roles: ["수석 기자", "구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-13.png",
    rank: 9,
    name: "마이크 맥그라스",
    media: "텔레그래프",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-14.png",
    rank: 10,
    name: "톰 개리",
    media: "텔레그래프",
    team: "여자축구",
    roles: ["여자축구 전담"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "텔레그래프",
    img: "../img/profile-img/face/face-16.png",
    rank: 11,
    name: "제레미 윌슨",
    media: "텔레그래프",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },

  // PA (Press Association)
  {
    id: "PA",
    img: "../img/profile-img/face/face-36.png",
    rank: 1,
    name: "사이먼 피치",
    media: "PA",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식", "독립 기고"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "PA",
    img: "../img/profile-img/face/face-37.png",
    rank: 2,
    name: "앤디 햄프슨",
    media: "PA",
    team: "맨체스터 시티",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "PA",
    img: "../img/profile-img/face/face-38.png",
    rank: 3,
    name: "칼 마크엄",
    media: "PA",
    team: "머지사이드",
    roles: ["리버풀, 에버튼 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "PA",
    img: "../img/profile-img/face/face-39.png",
    rank: 4,
    name: "마크 맨 브라이언스",
    media: "PA",
    team: "아스날",
    roles: ["구단 소식", "잉글랜드 국대"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "PA",
    img: "../img/profile-img/face/face-40.png",
    rank: 5,
    name: "조나단 빌",
    media: "PA",
    team: "토트넘",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },

  // The Guardian
  {
    id: "가디언",
    img: "../img/profile-img/face/face-04.png",
    rank: 1,
    name: "파브리지오 로마노",
    media: "가디언",
    team: "전체",
    roles: ["이적시장 전문보도", "독점 보도", "Here we go!"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-05.png",
    rank: 2,
    name: "제이콥 스테인버그",
    media: "가디언",
    team: "웨스트햄, 런던",
    roles: ["구단 소식", "웨스트햄, 첼시 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-06.png",
    rank: 3,
    name: "데이비드 하이트너",
    media: "가디언",
    team: "토트넘, 런던",
    roles: ["토트넘 전담", "런던팀 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-07.png",
    rank: 4,
    name: "닉 아메스",
    media: "가디언",
    team: "아스날",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-08.png",
    rank: 5,
    name: "앤디 헌터",
    media: "가디언",
    team: "머지사이드",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-09.png",
    rank: 6,
    name: "에드 아론스",
    media: "가디언",
    team: "아프리카",
    roles: ["아프리카 축구 전담"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "가디언",
    img: "../img/profile-img/face/face-22.png",
    rank: 7,
    name: "제이미 잭슨",
    media: "가디언",
    team: "EPL",
    roles: ["로마노 협업", "구단 소식"],
    trust: 60,
    profileUrl: "#",
  },

  // The Times
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-32.png",
    rank: 1,
    name: "마틴 지글러",
    media: "타임즈",
    team: "전체",
    roles: ["구단 소식", "구단 운영"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-42.png",
    rank: 2,
    name: "폴 조이스",
    media: "타임즈",
    team: "리버풀, 에버튼",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-52.png",
    rank: 3,
    name: "폴 허스트",
    media: "타임즈",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-02.png",
    rank: 4,
    name: "헨리 윈터",
    media: "타임즈",
    team: "아스날, 런던, 맨체스터 유나이티드",
    roles: ["아스날 전담", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-12.png",
    rank: 5,
    name: "게리 제이콥",
    media: "타임즈",
    team: "토트넘, 런던",
    roles: ["구단 소식", "독점 보도"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-13.png",
    rank: 6,
    name: "맷 로튼",
    media: "타임즈",
    team: "EPL",
    roles: ["수석 스포츠 특파원"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-14.png",
    rank: 7,
    name: "조나단 노스크로프트",
    media: "타임즈",
    team: "맨체스터, 머지사이드",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-24.png",
    rank: 8,
    name: "샬롯 던커",
    media: "타임즈",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-36.png",
    rank: 9,
    name: "콘스탄틴 에크너",
    media: "타임즈",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "타임즈",
    img: "../img/profile-img/face/face-48.png",
    rank: 10,
    name: "던컨 캐슬",
    media: "타임즈",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 20,
    profileUrl: "#",
  },

  // ESPN
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-56.png",
    rank: 1,
    name: "제임스 올리",
    media: "ESPN",
    team: "아스날, 첼시",
    roles: ["런던 전담", "구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-58.png",
    rank: 2,
    name: "마크 오그덴",
    media: "ESPN",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-12.png",
    rank: 3,
    name: "롭 도슨",
    media: "ESPN",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-13.png",
    rank: 4,
    name: "모이 요렌스",
    media: "ESPN",
    team: "바르셀로나",
    roles: ["스페인 특파원"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-21.png",
    rank: 5,
    name: "줄리앙 로렌스",
    media: "ESPN",
    team: "파리 생제르맹",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "ESPN",
    img: "../img/profile-img/face/face-14.png",
    rank: 6,
    name: "데일 존슨",
    media: "ESPN",
    team: "EPL",
    roles: ["UEFA 규정", "VAR 분석", "오프사이드 분석"],
    trust: 80,
    profileUrl: "#",
  },

  // Daily Mail
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-23.png",
    rank: 1,
    name: "사미 목벨",
    media: "데일리 메일",
    team: "런던",
    roles: ["런던팀 전담", "독점 보도"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-32.png",
    rank: 2,
    name: "마이크 키건",
    media: "데일리 메일",
    team: "맨체스터",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-33.png",
    rank: 3,
    name: "잭 고헌",
    media: "데일리 메일",
    team: "맨체스터 시티, 맨체스터",
    roles: ["맨시티 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-14.png",
    rank: 4,
    name: "도미닉 킹",
    media: "데일리 메일",
    team: "리버풀, 에버튼",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-12.png",
    rank: 5,
    name: "톰 콜로모세",
    media: "데일리 메일",
    team: "런던, 중부, 남부",
    roles: ["구단 소식"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-56.png",
    rank: 6,
    name: "크레이그 호프",
    media: "데일리 메일",
    team: "뉴캐슬, 북동부",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-51.png",
    rank: 7,
    name: "맷 휴즈",
    media: "데일리 메일",
    team: "리버풀",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-50.png",
    rank: 8,
    name: "맷 바로우",
    media: "데일리 메일",
    team: "첼시",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-11.png",
    rank: 9,
    name: "아드리안 카줌바",
    media: "데일리 메일",
    team: "전체",
    roles: ["구단 소식"],
    trust: 80,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-41.png",
    rank: 10,
    name: "롭 드레이퍼",
    media: "데일리 메일",
    team: "전체",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-44.png",
    rank: 11,
    name: "크리스 휠러",
    media: "데일리 메일",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-33.png",
    rank: 12,
    name: "이안 레이디먼",
    media: "데일리 메일",
    team: "맨체스터 유나이티드",
    roles: ["내부 기자 출신"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "데일리 메일",
    img: "../img/profile-img/face/face-22.png",
    rank: 13,
    name: "사이먼 존스",
    media: "데일리 메일",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 40,
    profileUrl: "#",
  },

  // The Independent
  {
    id: "인디펜던트",
    img: "../img/profile-img/face/face-50.png",
    rank: 1,
    name: "미구엘 델라니",
    media: "인디펜던트",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 40,
    profileUrl: "#",
  },
  {
    id: "풋볼 인사이더",
    img: "../img/profile-img/face/face-16.png",
    rank: 1,
    name: "피터 오 루크",
    media: "풋볼 인사이더",
    team: "토트넘",
    roles: ["독점 보도", "이적시장"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "풋볼 인사이더",
    img: "../img/profile-img/face/face-18.png",
    rank: 2,
    name: "션 피셔",
    media: "풋볼 인사이더",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 40,
    profileUrl: "#",
  },
  {
    id: "풋볼 인사이더",
    img: "../img/profile-img/face/face-23.png",
    rank: 3,
    name: "웨인 베이세이",
    media: "풋볼 인사이더",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 40,
    profileUrl: "#",
  },

  // The Sun
  {
    id: "더 선",
    img: "../img/profile-img/face/face-41.png",
    rank: 1,
    name: "찰리 와이어트",
    media: "더 선",
    team: "전체",
    roles: ["구단 소식"],
    trust: 20,
    profileUrl: "#",
  },
  {
    id: "더 선",
    img: "../img/profile-img/face/face-45.png",
    rank: 2,
    name: "닐 커스티스",
    media: "더 선",
    team: "맨체스터 유나이티드",
    roles: ["구단 소식", "날조왕"],
    trust: 20,
    profileUrl: "#",
  },
  {
    id: "더 선",
    img: "../img/profile-img/face/face-25.png",
    rank: 3,
    name: "앨런 닉슨",
    media: "더 선",
    team: "EPL",
    roles: ["구단 소식"],
    trust: 60,
    profileUrl: "#",
  },
  {
    id: "더 선",
    img: "../img/profile-img/face/face-14.png",
    rank: 4,
    name: "마틴 블랙번",
    media: "더 선",
    team: "맨체스터 시티",
    roles: ["맨시티 전담"],
    trust: 100,
    profileUrl: "#",
  },
  {
    id: "더 선",
    img: "../img/profile-img/face/face-26.png",
    rank: 5,
    name: "잭 로서",
    media: "더 선",
    team: "웨스트햄",
    roles: ["웨스트햄 전담"],
    trust: 100,
    profileUrl: "#",
  },
];

const tbody = document.querySelector(".table-wrap.trust .tbody");
const tabs = document.querySelectorAll(".tab-list button");

// 렌더링 함수
function renderTable(id) {
  const filtered = journalistData.filter((j) => j.id === id);
  tbody.innerHTML = filtered
    .map(
      (j) => `
    <li>
      <div class="order list">${j.rank}</div>
      <div class="report list">
        <p class="sub-profile C">
          <span class="img"><img src="${j.img}" alt="" /></span>
          <span class="name">${j.name}</span>
        </p>
      </div>
      <div class="media list">${j.media}</div>
      <div class="team list">${j.team}</div>
      <div class="field list">
        ${j.roles.map((r) => `<span>${r}</span>`).join("")}
      </div>
      <div class="trust list">
        <div class="chart-wrap">
          <div class="bar-bg">
            <div class="bar per-${j.trust}"></div>
          </div>
          <span class="percent">${j.trust}%</span>
        </div>
      </div>
      <div class="btn list">
        <a href="${j.profileUrl}" class="view-more">바로가기</a>
      </div>
    </li>
    `
    )
    .join("");
}

// 모든 .menu 요소를 찾음 (탭 그룹 단위)
const menus = document.querySelectorAll(".menu");

menus.forEach((menu) => {
  const tabs = menu.querySelectorAll(".tab-list button");

  tabs.forEach((btn) => {
    btn.addEventListener("click", () => {
      // 현재 menu 안의 탭 버튼들에서만 .on 제거
      tabs.forEach((b) => b.classList.remove("on"));

      // 클릭한 버튼에 .on 추가
      btn.classList.add("on");

      // 버튼 텍스트 (= id 값) 가져오기
      const selectedId = btn.textContent.trim();

      // 해당 menu와 연결된 테이블만 업데이트 (필요 시)
      renderTable(selectedId, menu);
    });
  });
});
// 첫 번째 탭(디 에슬레틱) 기본 렌더링
renderTable("디 애슬레틱");
